### ISSUE TITLE
Space Ruins not Spawning Properly

### ISSUE THREAD

**Issue by KateAnbolho** [Bubberstation/config#73]
Hey there, 

There's been about 4-5 days now of space ruins spawning in very light bunches of at most 8, compared to how they used to be (They used to take up an entire screen's worth of GPS space). The Config is still set to 80, is this intended?

Screenshots to confirm, and including the bare bottom that i've ever seen personally
https://i.gyazo.com/e464179e22e54c46e60c0b43a0f356f3.png
https://gyazo.com/7a5952509b18bd4a29f26b3af7aeec4f
https://i.gyazo.com/d3d2dfde3145216485a6186de5bbad7e.png

**Comment by Majkl-J** [comment]
There's been an edit without using the config repo as everyone with tgs access loves doing apparently. Updating this repo accordingly
